// Translate movie genres data
export const MoviesList = [
  { id: 28, name: "اکشن" },
  { id: 12, name: "ماجراجویی" },
  { id: 16, name: "انیمیشن" },
  { id: 35, name: "کمدی" },
  { id: 80, name: "جرایم" },
  { id: 99, name: "مستند" },
  { id: 18, name: "درام" },
  { id: 10751, name: "خانوادگی" },
  { id: 14, name: "فانتزی" },
  { id: 36, name: "تاریخی" },
  { id: 27, name: "ترسناک" },
  { id: 10402, name: "موزیک" },
  { id: 9648, name: "راز آلود" },
  { id: 10749, name: "عاشقانه" },
  { id: 878, name: "علمی تخیلی" },
  { id: 10770, name: "فیلم تلویزیونی" },
  { id: 53, name: "هیجان انگیز" },
  { id: 10752, name: "جنگی" },
  { id: 37, name: "غربی" },
];

// Translate tvshow genres data
export const TvList = [
  { id: 10759, name: "اکشن و ماجراجویی" },
  { id: 16, name: "انیمیشن" },
  { id: 35, name: "کمدی" },
  { id: 80, name: "جرایمی" },
  { id: 99, name: "مستند" },
  { id: 18, name: "درام" },
  { id: 10751, name: "خانوادگی" },
  { id: 10762, name: "کودکانه" },
  { id: 9648, name: "راز آلود" },
  { id: 10763, name: "اخبار" },
  { id: 10764, name: "واقعی" },
  { id: 10765, name: "علمی تخیلی و فانتزی" },
  { id: 10766, name: "داستانی" },
  { id: 10767, name: "گفتگو" },
  { id: 10768, name: "جنگی و سیاسی" },
  { id: 37, name: "غربی" },
];
